model_development:
  cooling:
    models:
      linear-regression:
        n_jobs: -1
      random-forest:
        n_estimators: 100
        n_jobs: -1
      xgboost:
        n_estimators: 100
        eval_metric: 'rmse'
    selector:
      best_model: 'xgboost'
      best_model_params:
        n_estimators: [50, 100, 200]
        learning_rate: [0.01, 0.1, 0.2]
        max_depth: [3, 5, 7]
        subsample: [0.8, 1.0]
        colsample_bytree: [0.8, 1.0]

  heating:
    models:
      linear-regression:
        n_jobs: -1
      random-forest:
        n_estimators: 100
        n_jobs: -1
      xgboost:
        n_estimators: 100
        eval_metric: 'rmse'
    selector:
      best_model: 'xgboost'
      best_model_params:
        n_estimators: [50, 100, 200]
        learning_rate: [0.01, 0.1, 0.2]
        max_depth: [3, 5, 7]
        subsample: [0.8, 1.0]
        colsample_bytree: [0.8, 1.0]