cooling_train:
  name: cooling
  grid:
    n_estimators: [50, 75, 100, 150, 200]
    learning_rate: [0.001, 0.01, 0.1, 0.2]
    max_depth: [3, 5, 7]
    subsample: [0.8, 1.0]
    colsample_bytree: [0.8, 1.0]

heating_train:
  name: heating
  grid:
    n_estimators: [50, 75, 100, 150, 200]
    learning_rate: [0.001, 0.01, 0.1, 0.2]
    max_depth: [3, 5, 7]
    subsample: [0.8, 1.0]
    colsample_bytree: [0.8, 1.0]