cooling_train:
  selector:
    grid:
      n_estimators: [50, 100, 200]
      learning_rate: [0.01, 0.1, 0.2]
      max_depth: [3, 5, 7]
      subsample: [0.8, 1.0]
      colsample_bytree: [0.8, 1.0]

heating_train:
  selector:
    grid:
      n_estimators: [50, 100, 200]
      learning_rate: [0.01, 0.1, 0.2]
      max_depth: [3, 5, 7]
      subsample: [0.8, 1.0]
      colsample_bytree: [0.8, 1.0]